- .npmignore
- package.json
remove the test script from npm package
bump latest version to 26
> Bump version and update ignore

- angular/_fonts.scss
- package.json
To match the react theme anti-aliasing (from the Heros anomaly)
> Add font anti-aliasing to angular theme

- CHANGELOG.md
- angular/theme.scss
- package.json
- Fixes #17 (wrong error color in angular theme)
- Minor version update
> Update Angular Theme Colors

- react/demo/src/pages/login.js
Fixes crash on CodeSandbox when opening the login dialog.
- remove the unneccessary HOC wrapper around the login component
> Remove unneccessary withRouter HOC

- react/demo/package.json
- react/demo/yarn.lock
#43 
Updated material-ui/core to latest to fix missing Slider import.
> Update material ui to latest

- storybook/CHANGELOG.md
- storybook/index.js
- storybook/package.json
- Add color to storybook hyperlinks that appear in READMEs
> Add blue color to hyperlinks

- storybook/index.js
- Current styles not being applied; this will work.
> Force hyperlink styles

- storybook/index.js
- This will update input fields' bg color to white instead of using CSS overrides in manager-head.html.
> White input for Storybook

- storybook/index.js
- Make the font weight lighter for Storybook Notes H1 section
> Set font weight to 400

- storybook/darkTheme.js
Fixes PXBLUE-1149.
- Update h1 font-weight for dark theme
> update h1 fontWeight

- angular/demo/yarn.lock
- angular/pxb-component-theme.scss
- angular/scripts/linkThemes.sh
- angular/theme.scss
- Update "scorecard" to "score-card" to match component class name.
- Pending: Ng Theme palette adjustments.
> Update 'scorecard' to 'score card'

- storybook/lightTheme.js
> Update tab bar to match our conventions in DSM

- angular/pxb-component-theme.scss
- Add theme for PX Blue ListItemTag.
> Add theme for ListItemTag

- angular/_darkTheme.scss
> Use `darkBlack` with a capital B

- .circleci/config.yml
- angular/_blueTheme.scss
- angular/_darkTheme.scss
- angular/_typography.scss
- package.json
- react/src/shared.ts
Fixes PXBLUE-1214
- add prettier check
> Add prettier to ci

- angular/pxb-component-theme.scss
Fixes #67  .
- Add rules to inherit text color for ILI instead of hardcoding to text color
> Make ILI inherit color

- angular/README.md
- Instruct users to apply angular theme to the body element instead of the app-root element so that overlay components are included in theme.
> Update theme instructions

- angular/_typography.scss
-  Remove uppercase text behavior from mat-button
> Remove uppercase btn theme

- angular/CHANGELOG.md
- angular/pxb-component-theme.scss
- Add pxblue theme to selected item in the rail
> Add background-color to selected rail-item

- angular/scripts/linkThemes.sh
- node_modules should not be copied into the demo node_modules folder
- make copy logic prettier
> Remove node_modules and condense copy logic

- angular/demos/theme/package.json
- angular/demos/theme/yarn.lock
- added yarn-audit-fix package to dev dependencies
- https://www.npmjs.com/package/yarn-audit-fix
- usage - yarn-audit-fix 
Themes>angular\demos\theme
108 vulnerabilities found
Severity: 95 Low | 3 Moderate | 10 High
After updates
9 vulnerabilities found
Severity: 3 Low | 2 Moderate | 4 High
> add yarn audit fix and update angular theme demo

- angular/CHANGELOG.md
- angular/_pxb-component-theme.scss
-  MobileStepper theme addition
https://pxblue-angular-library.web.app/?path=/story/components-mobile-stepper--with-full-config
> Add mobile stepper theme

- angular/_blueTheme.scss
- angular/_darkTheme.scss
Fixes #114 .
- Update specificity of stepper styles for Angular themes to avoid style conflicts with conditional buttons
> Update specificity of stepper styles for Angular themes to avoid style conflicts with conditional buttons

- .gitmodules
- .prettierignore
- react-native/package.json
- react-native/scripts/initializeSubmodule.sh
- react-native/scripts/linkThemes.sh
- Add the showcase repository as a submodule
- Update the linking scripts to inject the latest theme changes
> Add demo submodule for RN

- react-native/CHANGELOG.md
- react-native/dist/blueTheme.d.ts
- react-native/dist/blueTheme.js
- react-native/dist/index.js
- react-native/package.json
- react-native/src/blueTheme.ts
- react-native/yarn.lock
For PXBLUE-XXXX
- Allow version 3 or version 4 in the peerDependencies
- Update to new typescript version for compatibility
> Allow RN theme to work with RNP v4

- angular/CHANGELOG.md
- react-native/CHANGELOG.md
- react/CHANGELOG.md
- Update changelog for angular, react, rn themes
> Update changelog of active packages; deprecated changelog was not edited

- react-native/src/blueDarkTheme.ts
- Update showcase pointer
-  Remove unused color import
> Update showcase pointer

- react/CHANGELOG.md
- react/demos/theme/package.json
- react/demos/theme/src/App.js
- react/demos/theme/src/pages/overview.js
- react/demos/theme/src/pages/reports.js
- react/demos/theme/src/react-app-env.d.ts
- react/demos/theme/tsconfig.json
- react/demos/theme/yarn.lock
- react/dist/CHANGELOG.md
- react/dist/README.md
- react/dist/blueDarkTheme.js
- react/dist/blueTheme.js
- react/dist/package.json
- react/dist/shared.d.ts
- react/dist/shared.js
- react/package.json
- react/src/blueDarkTheme.ts
- react/src/blueTheme.ts
- react/src/shared.ts
- react/tsconfig.json
- react/yarn.lock
For PXBLUE-XXXX
- Updates to React light and dark theme to match the designs from Figma
- Made some variables for frequently re-used colors so we don't have to constantly use colors directly from the colors package (should make it easier to change things if we need to in the future)
- Dumped a bunch of components into the theme demo
> *NOTE*: I checked in the nasty updates to the theme demo to make testing easier, but we can back those out before merging into dev if we want...or we can leave it as a starting point for the Kitchen Sink update that we've been meaning to do.
> Updates to react themes (mostly dark, but also some light changes)

- react/demos/theme/src/App.js
- react/dist/blueDarkTheme.js
- react/dist/blueTheme.js
- react/src/blueDarkTheme.ts
- react/src/blueTheme.ts
For PXBLUE-1881
Fixes #138 
- Fix the border color issue for disabled text-variant button groups (primary and secondary)
before:
after:
> React theme cleanup items

- react/dist/blueDarkTheme.js
- react/dist/blueTheme.js
- react/dist/shared.d.ts
- react/dist/shared.js
- react/src/blueDarkTheme.ts
- react/src/blueTheme.ts
- Update secondary chip delete icons to follow the pattern from primary chips
> Fix color of delete icon in secondary chips

- angular/_typography.scss
> Make mat-body-2 font-weight 600

- react-native/README.md
- A little wordsmithing on the instructions
> Wordsmith the readme

- angular/theme.scss
- react-native/src/blueTheme.ts
Fixes # .
-  Update Angular and React-Native theme background color to white 200
> update to use white 200 for background

- react/demos/theme/src/App.js
- react/dist/blueTheme.js
- react/src/blueTheme.ts
> Fix primary and secondary flat buttons for React

- react-native/package.json
- react-native/src/blueDarkAltTheme.ts
- react-native/src/blueDarkTheme.ts
- react-native/src/blueTheme.ts
- react-native/src/index.ts
Fixes PXBLUE-1821.
- Add primaryBase and textSecondary custom colors for use with PXB components
> Add custom colors to the blueDarkTheme for use with PXB components

- react/demos/theme/src/App.js
- react/src/blueDarkTheme.ts
Fixes # .
- Fix underline color for filled input in dark react theme (red 500, 200 on hover)
> Fix underline color for filled input

- react-native/README.md
- react-native/package.json
- react-native/src/blueDarkTheme.ts
- react-native/src/blueTheme.ts
- react-native/src/index.ts
Fixes #94 
- Add bold font definition to RN theme
- Re-add type definition for RN themes
- Update submodules
> Update types for RN, add bold font definition

- react/CHANGELOG.md
- react/package.json
- react/yarn.lock
- Update dependencies used in the react theme
> Update react dependencies

- angular/CHANGELOG.md
- angular/package.json
Update Angular theme package version number to 6.0.0
> Update Angular theme package version number to 6.0.0

- .circleci/config.yml
- Change ci/cd workflow name so it makes more sense.
> Change workflow name from types to themes

- angular/_darkTheme.scss
- angular/_pxb-component-theme.scss
- Fix active drawer nav item icon color
> Fix active drawer nav item icon color

- .circleci/config.yml
- angular/CHANGELOG.md
- angular/_darkTheme.scss
- angular/_pxb-component-theme.scss
- angular/package.json
- angular/scripts/buildTest.sh
Fix build to release Angular Themes 6.0.1
> [NG-#1A]Release Angular Themes 6.0.1

- angular/CHANGELOG.md
> Fix changelog

- README.md
- angular/README.md
- package.json
- react-native/README.md
- react/README.md
- yarn.lock
- Update demo links so that they would point to <framework>-showcase-demo, the same link docit uses. The current link would not give the readers anything back.
- Some React Native theme doc still says we have no dark theme.
> Update demo links & descriptions about RN

- angular/CHANGELOG.md
- react-native/CHANGELOG.md
- react/CHANGELOG.md
- storybook/CHANGELOG.md
Fixes PXBLUE-1958
- Add package release dates to changelog
> Add package release date to changelog

- .circleci/config.yml
- angular/scripts/publish.sh
- react-native/scripts/publish.sh
- react/scripts/publish.sh
- storybook/scripts/publish.sh
- Allow publishing of alpha and beta packages from the dev branch automatically
- Add command line flag to publish script that takes in the current branch
- Default branch is master so that you can still run the publish command locally from another branch if necessary
> Add command line flag and dev branch publishing

- angular/PUBLISHING.md
- react-native/PUBLISHING.md
- react/PUBLISHING.md
- storybook/PUBLISHING.md
- Update publishing md description
> Update publishing instructions

- angular/_pxb-component-theme.scss
- Add styles to user menu bottomsheet
Can see in action here: https://pxblue-angular-library.web.app/?path=/story/*
> Add theme color for user menu bottom sheet

- angular/CHANGELOG.md
- angular/package.json
> Add changelog for 6.1.0

- angular/_blueTheme.scss
- angular/_darkTheme.scss
- Fix those dark theme disabled button styles for angular
- Hosted here: https://pxb-angular-theme-demo.web.app
> Fix dark mode disabled button styles
